/**
 * Created by lijin on 2017/6/22.
 */
var data={
    maxId:50,
    id:0,
    name:'全部文件',
    child:[
        {
            id:1,
            name:'男歌手',
            child:[
                {
                    id:1,
                    name:'周杰伦',
                    child:[
                        {
                            id:5,
                            name:'摩羯座',
                            child:[
                                {
                                    id:8,
                                    name:'黑色幽默',
                                    child:[]
                                },
                                {
                                    id:9,
                                    name:'晴天',
                                    child:[]
                                },
                                {
                                    id:10,
                                    name:'龙卷风',
                                    child:[]
                                }
                            ]
                        },
                        {
                            id:6,
                            name:'范特西',
                            child:[]
                        },
                        {
                            id:7,
                            name:'叶惠美',
                            child:[
                                {
                                    id:11,
                                    name:'双节棍',
                                    child:[]
                                },
                                {
                                    id:12,
                                    name:'安静',
                                    child:[]
                                },
                                {
                                    id:13,
                                    name:'借口',
                                    child:[]
                                }
                            ]
                        }
                    ]
                },
                {
                    id:2,
                    name:'五月天',
                    child:[
                        {
                            id:26,
                            name:'诺亚方舟',
                            child:[
                                {
                                    id:42,
                                    name:'你不是真正的快乐',
                                    child:[]
                                },
                                {
                                    id:43,
                                    name:'拥抱',
                                    child:[]
                                },
                                {
                                    id:44,
                                    name:'我不愿让你一个人',
                                    child:[]
                                }
                            ]
                        },
                        {
                            id:41,
                            name:'知足',
                            child:[
                                {
                                    id:45,
                                    name:'孙悟空',
                                    child:[]
                                },
                                {
                                    id:46,
                                    name:'知足',
                                    child:[]
                                },
                                {
                                    id:48,
                                    name:'恋爱ing',
                                    child:[]
                                }
                            ]
                        },
                        {
                            id:47,
                            name:'后青春期的诗',
                            child:[
                                {
                                    id:49,
                                    name:'突然好想你',
                                    child:[]
                                },
                                {
                                    id:50,
                                    name:'你不是真正的快乐',
                                    child:[]
                                }
                            ]
                        }
                    ]
                },
                {
                    id:4,
                    name:'林俊杰',
                    child:[
                        {
                            id:14,
                            name:'曹操',
                            child:[]
                        },
                        {
                            id:15,
                            name:'翅膀',
                            child:[]
                        },
                        {
                            id:16,
                            name:'冻结',
                            child:[]
                        },
                        {
                            id:17,
                            name:'美人鱼',
                            child:[]
                        }
                    ]
                }
            ]
        },
        {
            id:18,
            name:'女歌手',
            child:[
                {
                    id:3,
                    name:'梁静茹',
                    child:[
                        {
                            id:35,
                            name:'勇气',
                            child:[
                                {
                                    id:37,
                                    name:'爱你不是两三天',
                                    child:[]
                                },
                                {
                                    id:38,
                                    name:'勇气',
                                    child:[]
                                }
                            ]
                        },
                        {
                            id:36,
                            name:'亲亲',
                            child:[
                                {
                                    id:39,
                                    name:'暖暖',
                                    child:[]
                                },
                                {
                                    id:40,
                                    name:'小手拉大手',
                                    child:[]
                                }
                            ]
                        }
                    ]
                },
                {
                    id:19,
                    name:'孙燕姿',
                    child:[
                        {
                            id:21,
                            name:'逆光',
                            child:[
                                {
                                    id:22,
                                    name:'漩涡',
                                    child:[]
                                },
                                {
                                    id:23,
                                    name:'逆光',
                                    child:[]
                                },
                                {
                                    id:24,
                                    name:'关于',
                                    child:[]
                                }
                            ]
                        },
                        {
                            id:25,
                            name:'The Moment',
                            child:[
                                {
                                    id:27,
                                    name:'遇见',
                                    child:[]
                                },
                                {
                                    id:28,
                                    name:'天黑黑',
                                    child:[]
                                }
                            ]
                        },
                        {
                            id:34,
                            name:'离开',
                            child:[]
                        }
                    ]
                },
                {
                    id:20,
                    name:'蔡健雅',
                    child:[
                        {
                            id:29,
                            name:'失语者',
                            child:[
                                {
                                    id:31,
                                    name:'失语者',
                                    child:[]
                                }
                            ]
                        },
                        {
                            id:30,
                            name:'若你碰到他',
                            child:[
                                {
                                    id:32,
                                    name:'红色高跟鞋',
                                    child:[]
                                },
                                {
                                    id:33,
                                    name:'自由落体',
                                    child:[]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
};